import AppLayout from "@/components/AppLayout";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import {
  Plus, Clock, CheckCircle, AlertCircle, Calendar, FileText,
  Send, Eye, Edit, Trash2, Filter, Zap, Loader2, Inbox
} from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { Skeleton } from "@/components/ui/skeleton";

const statusColors: Record<string, string> = {
  pending: "bg-yellow-500/10 text-yellow-400 border-yellow-500/20",
  generating: "bg-blue-500/10 text-blue-400 border-blue-500/20",
  review: "bg-purple-500/10 text-purple-400 border-purple-500/20",
  published: "bg-green-500/10 text-green-400 border-green-500/20",
  failed: "bg-red-500/10 text-red-400 border-red-500/20",
};

const platformColors: Record<string, string> = {
  google: "bg-blue-500/10 text-blue-400",
  instagram: "bg-pink-500/10 text-pink-400",
  facebook: "bg-indigo-500/10 text-indigo-400",
  tiktok: "bg-violet-500/10 text-violet-400",
  youtube: "bg-red-500/10 text-red-400",
  reddit: "bg-orange-500/10 text-orange-400",
  wordpress: "bg-cyan-500/10 text-cyan-400",
};

export default function ContentHub() {
  const [createOpen, setCreateOpen] = useState(false);
  const [genPlatform, setGenPlatform] = useState("");
  const [genType, setGenType] = useState("");
  const [genTopic, setGenTopic] = useState("");
  const [genContent, setGenContent] = useState("");
  const [genTitle, setGenTitle] = useState("");

  const { data: queueData, isLoading } = trpc.content.queue.useQuery();
  const utils = trpc.useUtils();

  const createMutation = trpc.content.create.useMutation({
    onSuccess: () => {
      setCreateOpen(false);
      toast.success("Post added to queue");
      utils.content.queue.invalidate();
      resetForm();
    },
    onError: (err) => toast.error(err.message),
  });

  const generateMutation = trpc.content.generate.useMutation({
    onSuccess: (data) => {
      setGenTitle(data.title);
      setGenContent(data.content);
      toast.success("Content generated by AI!");
      utils.content.queue.invalidate();
    },
    onError: (err) => toast.error(`Generation failed: ${err.message}`),
  });

  const processQueueMutation = trpc.content.processQueue.useMutation({
    onSuccess: (data) => {
      toast.success(`Processed: ${data.processed} published, ${data.failed} failed, ${data.skipped} retrying`);
      utils.content.queue.invalidate();
    },
    onError: (err) => toast.error(`Queue processing failed: ${err.message}`),
  });

  const updateStatusMutation = trpc.content.updateStatus.useMutation({
    onSuccess: () => {
      utils.content.queue.invalidate();
      toast.success("Status updated");
    },
  });

  const resetForm = () => {
    setGenPlatform("");
    setGenType("");
    setGenTopic("");
    setGenContent("");
    setGenTitle("");
  };

  const handleAIGenerate = () => {
    if (!genPlatform) { toast.error("Select a platform first"); return; }
    generateMutation.mutate({
      platform: genPlatform,
      contentType: genType || "social",
      topic: genTopic || undefined,
    });
  };

  const handleCreate = () => {
    if (!genPlatform) { toast.error("Select a platform"); return; }
    if (!genContent && !genTitle) { toast.error("Generate or write content first"); return; }
    createMutation.mutate({
      platform: genPlatform,
      contentType: genType || "social",
      title: genTitle || undefined,
      content: genContent || undefined,
    });
  };

  // Split data into queue (pending/generating/review) and published
  const pendingItems = queueData?.filter(c => c.status !== "published" && c.status !== "failed") || [];
  const publishedItems = queueData?.filter(c => c.status === "published") || [];
  const failedItems = queueData?.filter(c => c.status === "failed") || [];

  return (
    <AppLayout>
      <div className="space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold">Content Hub</h1>
            <p className="text-muted-foreground text-sm mt-1">Manage your content queue and publishing pipeline</p>
          </div>
          <div className="flex gap-3">
            <Button
              variant="outline"
              size="sm"
              onClick={() => processQueueMutation.mutate()}
              disabled={processQueueMutation.isPending}
            >
              {processQueueMutation.isPending ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Send className="w-4 h-4 mr-2" />}
              Process Queue
            </Button>
            <Dialog open={createOpen} onOpenChange={setCreateOpen}>
              <DialogTrigger asChild>
                <Button size="sm" className="gradient-orange text-black font-semibold hover:opacity-90">
                  <Plus className="w-4 h-4 mr-2" /> Create Post
                </Button>
              </DialogTrigger>
              <DialogContent className="bg-card border-border max-w-lg">
                <DialogHeader>
                  <DialogTitle>Create New Content</DialogTitle>
                </DialogHeader>
                <div className="space-y-4 pt-2">
                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <Label className="text-xs">Platform</Label>
                      <Select value={genPlatform} onValueChange={setGenPlatform}>
                        <SelectTrigger className="mt-1"><SelectValue placeholder="Select..." /></SelectTrigger>
                        <SelectContent>
                          <SelectItem value="google">Google Business</SelectItem>
                          <SelectItem value="instagram">Instagram</SelectItem>
                          <SelectItem value="facebook">Facebook</SelectItem>
                          <SelectItem value="tiktok">TikTok</SelectItem>
                          <SelectItem value="youtube">YouTube</SelectItem>
                          <SelectItem value="reddit">Reddit</SelectItem>
                          <SelectItem value="wordpress">WordPress</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                    <div>
                      <Label className="text-xs">Content Type</Label>
                      <Select value={genType} onValueChange={setGenType}>
                        <SelectTrigger className="mt-1"><SelectValue placeholder="Select..." /></SelectTrigger>
                        <SelectContent>
                          <SelectItem value="social">Social Post</SelectItem>
                          <SelectItem value="blog">Blog Article</SelectItem>
                          <SelectItem value="video">Video Script</SelectItem>
                          <SelectItem value="schema">Schema Markup</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  </div>
                  <div>
                    <Label className="text-xs">Topic (optional)</Label>
                    <Input className="mt-1" placeholder="e.g., 5 tips for better SEO" value={genTopic} onChange={e => setGenTopic(e.target.value)} />
                  </div>
                  <Button
                    variant="outline"
                    className="w-full border-primary/30 text-primary hover:bg-primary/10"
                    onClick={handleAIGenerate}
                    disabled={generateMutation.isPending}
                  >
                    {generateMutation.isPending ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Zap className="w-4 h-4 mr-2" />}
                    {generateMutation.isPending ? "Generating..." : "AI Generate Content"}
                  </Button>
                  {genTitle && (
                    <div>
                      <Label className="text-xs">Title</Label>
                      <Input className="mt-1" value={genTitle} onChange={e => setGenTitle(e.target.value)} />
                    </div>
                  )}
                  {genContent && (
                    <div>
                      <Label className="text-xs">Content</Label>
                      <Textarea className="mt-1 min-h-[120px]" value={genContent} onChange={e => setGenContent(e.target.value)} />
                    </div>
                  )}
                  <Button
                    className="w-full gradient-orange text-black font-semibold hover:opacity-90"
                    onClick={handleCreate}
                    disabled={createMutation.isPending || (!genContent && !genTitle)}
                  >
                    {createMutation.isPending ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Plus className="w-4 h-4 mr-2" />}
                    Add to Queue
                  </Button>
                </div>
              </DialogContent>
            </Dialog>
          </div>
        </div>

        <Tabs defaultValue="queue" className="space-y-4">
          <TabsList className="bg-secondary border border-border">
            <TabsTrigger value="queue" className="data-[state=active]:bg-primary/10 data-[state=active]:text-primary">
              <Clock className="w-4 h-4 mr-2" /> Queue ({pendingItems.length})
            </TabsTrigger>
            <TabsTrigger value="published" className="data-[state=active]:bg-primary/10 data-[state=active]:text-primary">
              <CheckCircle className="w-4 h-4 mr-2" /> Published ({publishedItems.length})
            </TabsTrigger>
            <TabsTrigger value="failed" className="data-[state=active]:bg-primary/10 data-[state=active]:text-primary">
              <AlertCircle className="w-4 h-4 mr-2" /> Failed ({failedItems.length})
            </TabsTrigger>
          </TabsList>

          {/* Queue Tab */}
          <TabsContent value="queue" className="space-y-3">
            {isLoading ? (
              Array.from({ length: 3 }).map((_, i) => (
                <Card key={i} className="bg-card border-border">
                  <CardContent className="p-4"><Skeleton className="h-12 w-full" /></CardContent>
                </Card>
              ))
            ) : pendingItems.length === 0 ? (
              <Card className="bg-card border-border">
                <CardContent className="p-8 flex flex-col items-center justify-center text-muted-foreground">
                  <Inbox className="w-10 h-10 mb-3 opacity-30" />
                  <p className="font-medium">Queue is empty</p>
                  <p className="text-sm mt-1">Create content or use AI Generate to add items</p>
                </CardContent>
              </Card>
            ) : (
              pendingItems.map((item) => (
                <Card key={item.id} className="bg-card border-border">
                  <CardContent className="p-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-3 flex-1">
                        <div className={`w-9 h-9 rounded-lg flex items-center justify-center ${platformColors[item.platform] || "bg-muted"}`}>
                          <FileText className="w-4 h-4" />
                        </div>
                        <div className="flex-1 min-w-0">
                          <p className="font-medium text-sm truncate">{item.title || "Untitled content"}</p>
                          <div className="flex items-center gap-2 mt-1">
                            <Badge variant="outline" className={`text-[10px] ${platformColors[item.platform]}`}>{item.platform}</Badge>
                            <Badge variant="outline" className="text-[10px]">{item.contentType || "social"}</Badge>
                            {item.scheduledFor && (
                              <span className="text-xs text-muted-foreground">
                                {new Date(item.scheduledFor).toLocaleString()}
                              </span>
                            )}
                          </div>
                        </div>
                      </div>
                      <div className="flex items-center gap-2">
                        <Badge variant="outline" className={statusColors[item.status || "pending"]}>{item.status}</Badge>
                        <Button variant="ghost" size="sm" className="h-8 w-8 p-0"
                          onClick={() => updateStatusMutation.mutate({ id: item.id, status: "published" })}
                          title="Mark as published">
                          <CheckCircle className="w-4 h-4" />
                        </Button>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))
            )}
          </TabsContent>

          {/* Published Tab */}
          <TabsContent value="published" className="space-y-3">
            {publishedItems.length === 0 ? (
              <Card className="bg-card border-border">
                <CardContent className="p-8 flex flex-col items-center justify-center text-muted-foreground">
                  <CheckCircle className="w-10 h-10 mb-3 opacity-30" />
                  <p className="font-medium">No published content yet</p>
                  <p className="text-sm mt-1">Process your queue to publish content</p>
                </CardContent>
              </Card>
            ) : (
              publishedItems.map((item) => (
                <Card key={item.id} className="bg-card border-border">
                  <CardContent className="p-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-3 flex-1">
                        <div className={`w-9 h-9 rounded-lg flex items-center justify-center ${platformColors[item.platform] || "bg-muted"}`}>
                          <CheckCircle className="w-4 h-4" />
                        </div>
                        <div className="flex-1 min-w-0">
                          <p className="font-medium text-sm truncate">{item.title || "Untitled"}</p>
                          <div className="flex items-center gap-2 mt-1">
                            <Badge variant="outline" className={`text-[10px] ${platformColors[item.platform]}`}>{item.platform}</Badge>
                            {item.publishedAt && (
                              <span className="text-xs text-muted-foreground">
                                Published {new Date(item.publishedAt).toLocaleString()}
                              </span>
                            )}
                          </div>
                        </div>
                      </div>
                      <Badge variant="outline" className={statusColors.published}>published</Badge>
                    </div>
                  </CardContent>
                </Card>
              ))
            )}
          </TabsContent>

          {/* Failed Tab */}
          <TabsContent value="failed" className="space-y-3">
            {failedItems.length === 0 ? (
              <Card className="bg-card border-border">
                <CardContent className="p-8 flex flex-col items-center justify-center text-muted-foreground">
                  <AlertCircle className="w-10 h-10 mb-3 opacity-30" />
                  <p className="font-medium">No failed items</p>
                </CardContent>
              </Card>
            ) : (
              failedItems.map((item) => (
                <Card key={item.id} className="bg-card border-border border-red-500/20">
                  <CardContent className="p-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-3 flex-1">
                        <div className="w-9 h-9 rounded-lg flex items-center justify-center bg-red-500/10">
                          <AlertCircle className="w-4 h-4 text-red-400" />
                        </div>
                        <div className="flex-1 min-w-0">
                          <p className="font-medium text-sm truncate">{item.title || "Untitled"}</p>
                          <p className="text-xs text-red-400 mt-1">{item.errorLog || "Unknown error"}</p>
                        </div>
                      </div>
                      <Button variant="outline" size="sm"
                        onClick={() => updateStatusMutation.mutate({ id: item.id, status: "pending" })}>
                        Retry
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              ))
            )}
          </TabsContent>
        </Tabs>
      </div>
    </AppLayout>
  );
}
